#!/usr/bin/env bash
set -Eeuo pipefail

# Generated by scripts/release.py; trust anchors come from start.sh.
START_SH_VERSION="1.5.1"
REPO_URL="https://raw.githubusercontent.com/jedarden/harnessctl/main"
ARTIFACT_MANIFEST_FILE="artifact-manifest.txt"
ARTIFACT_SIGNATURE_FILE="artifact-manifest.sig"
ARTIFACT_TRUSTED_KEY_ID="bootstrap-rsa-2026-10"
ARTIFACT_TRUSTED_PUBLIC_KEY=$(cat <<'ARTIFACT_KEY'
-----BEGIN PUBLIC KEY-----
MIIBojANBgkqhkiG9w0BAQEFAAOCAY8AMIIBigKCAYEApNHGqYPfKvRpLulWXS8c
/VuKITatXEhDqrXY4/0ug9SqlZF8e/o3q6FVgbMqdRTniDOrhgx1mUcbzpFJ4Y6Z
ILcYmIEXne12A2BxHh2SF+9uXBAbwNdlEIXunybhGT4te32UKGGqRN7TdFpr6KsN
nSSNN2/WyvjL+ytqpa2KyguXkrGHSfwDdUDKDGYmL1eZHjhP2GrWxG6aI8EcMtfp
mAy/NUXxL2tOB8bGz+IPfTsycwcDqZ0mw59vQUy2+nUTnG/xQpWud6SXPMuSJoJ9
3tGGU24gz4vptPn7V/L3rGQp8Titgks0IxpwEXZV2T//wNEXBebGUGaoQfOrGSoC
AzELsxvleqZOKRJyP55Djqh5iELC9tF9yxmCmRLxYwUzYPz234Wf2E0Qi1Vo386e
VxyDwlCe9IIMEgejVkjseahaS5INmFjCoDjH7cZWY28MtTVy1u9/79n6wBkApJeQ
7AuWeqPskkNYJz18R2aRjER6/Ru+2gyXw5fnD3RbpLfzAgMBAAE=
-----END PUBLIC KEY-----
ARTIFACT_KEY
)
ARTIFACT_TRUSTED_KEY_IDS=("$ARTIFACT_TRUSTED_KEY_ID")
ARTIFACT_TRUSTED_PUBLIC_KEYS=("$ARTIFACT_TRUSTED_PUBLIC_KEY")

UPDATE_REPO_URL="$REPO_URL"
verify_artifact_manifest() {
    local directory=$1 manifest="$1/$ARTIFACT_MANIFEST_FILE"
    local signature="$1/$ARTIFACT_SIGNATURE_FILE" public_key="$1/public-key.pem"
    local key_id signature_key_id signature_value manifest_version trusted_public_key

    command -v curl >/dev/null 2>&1 || {
        echo "Update metadata error: curl is not installed." >&2
        return 1
    }
    command -v openssl >/dev/null 2>&1 || {
        echo "Update metadata error: openssl is not installed." >&2
        return 1
    }
    openssl version >/dev/null 2>&1 || {
        echo "Update metadata error: openssl exists but cannot run; check its shared libraries." >&2
        return 1
    }
    command -v base64 >/dev/null 2>&1 || {
        echo "Update metadata error: base64 is not installed." >&2
        return 1
    }
    command -v sha256sum >/dev/null 2>&1 || {
        echo "Update metadata error: sha256sum is not installed." >&2
        return 1
    }
    if ! curl -sfL --connect-timeout 5 --max-time 20 "$UPDATE_REPO_URL/$ARTIFACT_MANIFEST_FILE" > "$manifest" 2>/dev/null; then
        echo "Update metadata error: could not download $ARTIFACT_MANIFEST_FILE from the configured source." >&2
        return 1
    fi
    if ! curl -sfL --connect-timeout 5 --max-time 20 "$UPDATE_REPO_URL/$ARTIFACT_SIGNATURE_FILE" > "$signature" 2>/dev/null; then
        echo "Update metadata error: could not download $ARTIFACT_SIGNATURE_FILE from the configured source." >&2
        return 1
    fi
    mapfile -t key_ids < <(grep -E '^key_id=[A-Za-z0-9._-]+$' "$manifest" || true)
    if [[ ${#key_ids[@]} -ne 1 ]]; then
        echo "Update metadata error: the release manifest has no single valid key ID." >&2
        return 1
    fi
    key_id=${key_ids[0]#key_id=}
    trusted_public_key=""
    for key_index in "${!ARTIFACT_TRUSTED_KEY_IDS[@]}"; do
        if [[ "$key_id" == "${ARTIFACT_TRUSTED_KEY_IDS[$key_index]}" ]]; then
            trusted_public_key="${ARTIFACT_TRUSTED_PUBLIC_KEYS[$key_index]}"
            break
        fi
    done
    if [[ -z "$trusted_public_key" ]]; then
        echo "Update metadata error: release key '$key_id' is not trusted by this launcher." >&2
        return 1
    fi
    printf '%s\n' "$trusted_public_key" > "$public_key"

    mapfile -t signature_ids < <(grep -E '^key_id=[A-Za-z0-9._-]+$' "$signature" || true)
    if [[ ${#signature_ids[@]} -ne 1 ]]; then
        echo "Update metadata error: the detached signature has no single valid key ID." >&2
        return 1
    fi
    signature_key_id=${signature_ids[0]#key_id=}
    if [[ "$signature_key_id" != "$key_id" ]]; then
        echo "Update metadata error: manifest and signature key IDs differ." >&2
        return 1
    fi
    mapfile -t signatures < <(grep -E '^signature=[A-Za-z0-9+/]+=*$' "$signature" || true)
    if [[ ${#signatures[@]} -ne 1 ]]; then
        echo "Update metadata error: the detached signature payload is malformed." >&2
        return 1
    fi
    signature_value=${signatures[0]#signature=}
    if ! printf '%s' "$signature_value" | base64 --decode > "$directory/signature.bin" 2>/dev/null; then
        echo "Update metadata error: the detached signature is not valid base64." >&2
        return 1
    fi
    if ! openssl dgst -sha256 -verify "$public_key" -signature "$directory/signature.bin" "$manifest" >/dev/null 2>&1; then
        echo "Update metadata error: release manifest signature verification failed." >&2
        return 1
    fi

    if [[ "$(sed -n 's/^format=//p' "$manifest")" != "harnessctl-artifacts-v1" ]]; then
        echo "Update metadata error: the signed manifest uses an unsupported format." >&2
        return 1
    fi
    mapfile -t manifest_versions < <(grep -E '^version=[0-9]+\.[0-9]+\.[0-9]+$' "$manifest" || true)
    if [[ ${#manifest_versions[@]} -ne 1 ]]; then
        echo "Update metadata error: the signed manifest has no single semantic version." >&2
        return 1
    fi
    manifest_version=${manifest_versions[0]#version=}
    printf '%s\n' "$manifest_version"
}

manifest_artifact_hash() {
    local manifest=$1 artifact=$2
    mapfile -t hashes < <(grep -E "^artifact=${artifact//./\.} [0-9a-f]{64}$" "$manifest" || true)
    [[ ${#hashes[@]} -eq 1 ]] || return 1
    printf '%s\n' "${hashes[0]##* }"
}

verify_artifact_file() {
    local manifest=$1 artifact=$2 path=$3 expected actual payload_version
    expected=$(manifest_artifact_hash "$manifest" "$artifact") || return 1
    actual=$(sha256sum "$path" | awk '{print $1}') || return 1
    [[ "$actual" == "$expected" ]] || return 1
    if [[ "$artifact" == "start.sh" ]]; then
        mapfile -t payload_versions < <(grep -E '^START_SH_VERSION="[0-9]+\.[0-9]+\.[0-9]+"$' "$path" || true)
        [[ ${#payload_versions[@]} -eq 1 ]] || return 1
        payload_version=${payload_versions[0]#START_SH_VERSION=\"}
        payload_version=${payload_version%\"}
        [[ "$payload_version" == "$(grep -E '^version=' "$manifest" | cut -d= -f2)" ]] || return 1
    fi
}



script_path="${START_SH_INSTALL_PATH:-$HOME/start.sh}"
bin_dir="${START_SH_BIN_DIR:-$HOME/.local/bin}"
while [[ $# -gt 0 ]]; do
    case "$1" in
        --script-path|--bin-dir|--source)
            [[ $# -ge 2 && -n "$2" ]] || { echo "Error: $1 requires a value" >&2; exit 2; }
            case "$1" in
                --script-path) script_path="$2" ;;
                --bin-dir) bin_dir="$2" ;;
                --source) UPDATE_REPO_URL="${2%/}" ;;
            esac
            shift 2
            ;;
        --version|-v) echo "harnessctl installer v$START_SH_VERSION"; exit 0 ;;
        --help|-h)
            cat <<'HELP'
Usage: bash install.sh [OPTIONS]

Authenticate and install the signed harnessctl launcher.

Options:
  --script-path PATH  Launcher destination (default: ~/start.sh)
  --bin-dir DIR       Directory for the start symlink (default: ~/.local/bin)
  --source URL        Signed release root containing the manifest and artifacts
  --version, -v       Print the installer version and exit
  --help, -h          Show this help and exit

Environment equivalents:
  START_SH_INSTALL_PATH  Launcher destination
  START_SH_BIN_DIR       Directory for the start symlink
HELP
            exit 0
            ;;
        *) echo "Error: unknown option: $1" >&2; exit 2 ;;
    esac
done
for dependency in curl openssl sha256sum base64 bash; do
    command -v "$dependency" >/dev/null 2>&1 || { echo "Error: $dependency is required" >&2; exit 1; }
done
openssl version >/dev/null 2>&1 || {
    echo 'Error: openssl exists but cannot run; check its shared libraries' >&2
    exit 1
}

mkdir -p "$(dirname "$script_path")" "$bin_dir"
script_path="$(readlink -m "$script_path")"
bin_dir="$(cd "$bin_dir" && pwd -P)"
link="$bin_dir/start"
if [[ (-e "$link" || -L "$link") && "$(readlink -f "$link" 2>/dev/null || true)" != "$script_path" ]]; then
    echo "Error: $link already belongs to another command" >&2
    exit 1
fi
if command -v git >/dev/null 2>&1 &&
    git -C "$(dirname "$script_path")" ls-files --error-unmatch "$(basename "$script_path")" >/dev/null 2>&1; then
    echo 'Error: install to a deployed location outside tracked source files' >&2
    exit 1
fi
work=$(mktemp -d "${script_path}.install.XXXXXX")
trap 'rm -rf "$work"' EXIT
version=$(verify_artifact_manifest "$work") || { echo 'Error: release signature verification failed' >&2; exit 1; }
curl -fsSL --connect-timeout 5 --max-time 30 "$UPDATE_REPO_URL/start.sh" > "$work/start.sh"
verify_artifact_file "$work/$ARTIFACT_MANIFEST_FILE" start.sh "$work/start.sh" || {
    echo 'Error: launcher does not match the signed release' >&2; exit 1;
}
bash -n "$work/start.sh"
# Refuse downgrades, including when installing a pinned older release.
if [[ -f "$script_path" ]]; then
    installed=$(sed -n 's/^START_SH_VERSION="\([0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\)"$/\1/p' "$script_path")
    if [[ -n "$installed" && "$installed" != "$version" &&
          "$(printf '%s\n%s\n' "$installed" "$version" | sort -V | head -1)" == "$version" ]]; then
        echo "Error: refusing to replace installed $installed with older $version" >&2
        exit 1
    fi
fi
chmod 0755 "$work/start.sh"
mv -f "$work/start.sh" "$script_path"
[[ -L "$link" ]] || ln -s "$script_path" "$link"
echo "Installed start v$version: $link -> $script_path"
echo 'Run start doctor, start claude, or start codex.'
case ":$PATH:" in *":$bin_dir:"*) ;; *) printf 'Add to your shell PATH: export PATH=%q:$PATH\n' "$bin_dir" ;; esac
